# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdshader-language-server" do
  desc ""
  homepage ""
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdshader-language-server"

  on_macos do
    on_intel do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Darwin_x86_64.tar.gz"
      sha256 "fb13853ad9f52b5240015fdc9a17c3dfbeae8c061c61d6c782bf286e6481199b"
    end
    on_arm do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Darwin_arm64.tar.gz"
      sha256 "45aec0a5a79c85687bd03f164b537cf92848cbd97f476416734ba1144a6cd32f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Linux_x86_64.tar.gz"
      sha256 "8780731c2f45c81204f88471df5e2c7ddf07a66879e9a07db66912a179999235"
    end
    on_arm do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Linux_arm64.tar.gz"
      sha256 "5dc220554363e4e5262d3cfa605ef99905f8fced38097bdc85955d7d2a26340d"
    end
  end

  # No zap stanza required
end
