# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdshader-language-server" do
  desc "Language server for .gdshader files"
  homepage "https://github.com/armsnyder/gdshader-language-server"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdshader-language-server"

  on_macos do
    on_intel do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Darwin_x86_64.tar.gz"
      sha256 "a831fe5240b18ecbb2c481edce4114592d6c5a410e85df6f41646b31ab7c164e"
    end
    on_arm do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Darwin_arm64.tar.gz"
      sha256 "a9bdeeb740b6000f90b2616d548ee2fbc8e56cefc47200f1f7874df9fe1d297b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Linux_x86_64.tar.gz"
      sha256 "c3cc7da369dcc86e11d221862735678f449c8260ace0ca527fb95a8526571f3e"
    end
    on_arm do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Linux_arm64.tar.gz"
      sha256 "4113ff55b0abec621f5041c89c17186d9049419fb36c2c1235baad18c274c0f8"
    end
  end

  # No zap stanza required
end
