# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdshader-language-server" do
  desc "Language server for .gdshader files"
  homepage "https://github.com/armsnyder/gdshader-language-server"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdshader-language-server"

  on_macos do
    on_intel do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Darwin_x86_64.tar.gz"
      sha256 "635b47ce6973ee12016ac44206064783de96894196e0b171dd7c3319e4f4a4ac"
    end
    on_arm do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Darwin_arm64.tar.gz"
      sha256 "02186949a1bea3e84cc7a49418b320a1b88fc409a87302ea1f204821cb636683"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Linux_x86_64.tar.gz"
      sha256 "f708c2568ab1e1a4d3158156eb52d7febea4a5fd6b62a6d278faecb4b29a3eb6"
    end
    on_arm do
      url "https://github.com/armsnyder/gdshader-language-server/releases/download/v0.6.0/gdshader-language-server_Linux_arm64.tar.gz"
      sha256 "1ea7184c3c5070115bb9797608e63f482daf4e65fac21d0cdf0017316468dab0"
    end
  end

  # No zap stanza required
end
